# Generated by Django 2.1.4 on 2019-05-11 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='note_1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
