# Generated by Django 2.1.4 on 2019-05-11 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0002_choice_note_1'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='note_2',
            field=models.TextField(blank=True, null=True),
        ),
    ]
