# Generated by Django 2.1.4 on 2019-05-12 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0004_choice_note_3'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='imag_5',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='imag_5_url',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
        migrations.AddField(
            model_name='choice',
            name='imag_6',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='choice',
            name='imag_6_url',
            field=models.CharField(blank=True, max_length=90, null=True),
        ),
    ]
