# Generated by Django 2.1.4 on 2019-05-12 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20190512_1329'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='mood',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
