# Generated by Django 2.1.4 on 2019-05-08 18:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imag_1', models.IntegerField(default=0)),
                ('imag_2', models.IntegerField(default=0)),
                ('imag_3', models.IntegerField(default=0)),
                ('imag_4', models.IntegerField(default=0)),
                ('date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
            ],
        ),
    ]
